---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-monitoring
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 10s
  path: ./infrastructure/dev/nginx-monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: nginx
    - name: monitoring
