---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  values:
    alertmanager:
      ingress:
        hosts:
          - alertmanager.cluster.local
    grafana:
      ingress:
        hosts:
          - grafana.cluster.local
    prometheus:
      ingress:
        hosts:
          - prometheus.cluster.local
