---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karma
  namespace: monitoring
spec:
  rules:
    - host: karma.cluster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: karma
                port:
                  number: 80
