---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: nginx
  chart:
    spec:
      version: 4.x
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 60m
  install:
    crds: Create
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
  values:
    controller:
      annotations:
        # Scrape nginx controller pod for metrics.
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
      extraArgs:
        default-ssl-certificate: nginx/default-ssl-certificate
