---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - port: metrics
      interval: 1s
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: metrics
      port: 10254
