---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-helm-repo.yaml
  - flux-monitoring-config.yaml
  - flux-monitoring-repo.yaml
  - helm-release-blackbox-exporter.yaml
  - helm-release-prometheus.yaml
  - helm-release-thanos.yaml
  - karma.yaml
  - metrics-server-monitor.yaml
  - metrics-storage-secret.yaml
  - namespace.yaml
  - prometheus-community-helm-repo.yaml
