apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore
  namespace: monitoring
data:
  objstore.yml: dHlwZTogUzMKY29uZmlnOgogIGJ1Y2tldDogdGhhbm9zCiAgZW5kcG9pbnQ6IG1pbmlvLWFwaS5kZXYuc3ZjLmNsdXN0ZXIubG9jYWwKICBhY2Nlc3Nfa2V5OiBhY2Nlc3MwMTIzNDU2Nzg5CiAgc2VjcmV0X2tleTogc2VjcmV0MDEyMzQ1Njc4OQogIGluc2VjdXJlOiB0cnVlCg==
type: Opaque
#
# type: S3
# config:
#   bucket: thanos
#   endpoint: minio-api.dev.svc.cluster.local
#   access_key: access0123456789
#   secret_key: secret0123456789
#   insecure: true
#
# kubectl create secret -n monitoring generic thanos-objstore --from-file=objstore.yml=objstore.yml
#
